avatar: 
  image_type_accept: image/jpeg,image/gif,image/png
  image_size_edit: "50x50"
  image_size: "200x200"
  image_storage: 5
  store_dir: "uploads/#{model.class.to_s.underscore}/#{mounted_as}/#{model.id}"
  extension_white_list:
    - jpg
    - jpeg
    - gif
    - png
per_page: 10
maximum_category_name_length: 100
questions_per_exam: 5
exams:
  start: "Start"
  view: "View"
  minutes: 3
